### ISSUE TITLE
Error message even repo is valid and cloning works

### ISSUE THREAD

**Issue by Alex9779** [tohara/OctoPrint-BigBoxFirmware#5]
When adding a new repository I always get an error message in the console output right after starting even the whole process works:

```
Starting....
 is not a valid Github repo or no internet connection.
Cloning into 'Marlin'...
POST git-upload-pack (gzip 1224 to 639 bytes)
remote: Counting objects: 39798, done.[K
```

**Comment by tohara** [comment]
When I tested this right after I saw you message i got the same error message, but when I decided to debug it and get it fixed today I do not get this message.

The only way I am able to replicate it is by manually adding an empty folder under ~/.octoprint/data/bigboxfirmware/repos/<githubUser>/

This message is not from adding a new repo since that is working, but from the code run before, checking if any repos should be removed. I will look into creating some code that will handle folders without valid git info.

**Comment by tohara** [comment]
I think found what is cause of this. If a git repo define in a profile does not exist a folder would be created for it. I have fixed this, but ypu might have to ssh into ~/.octoprint/data/bigboxfirmware/repos/ and delete any empty folders.

**Comment by tohara** [comment]
Are you still getting this?

**Comment by Alex9779** [comment]
Don't think so, lets close it...
